version: '3.6'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - ${PWD}/db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=keeply
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5466:5432
    networks:
      - default
    restart: always

  mongodb:
    image: mongo:6.0.1
    container_name: mongodb
    volumes:
      - ${PWD}/db/mongo:/data/db
    ports:
      - 27018:27017 
    networks:
      - default
    restart: always